### PR TITLE
Add PathAccessible for easy accessing through path with key and index

### PR DESCRIPTION
**Pull request by onmyway133**
So that we can use it like

```swift
self.secret <- map.path(["chaos", 1, "way", "light", 1])?.property("secret")
```

Initially, I want to use variadic parameter instead of array, but it seems to not work with these `LiteralConvertible` https://github.com/onmyway133/issues/issues/133

### CODE REVIEW

**Comment by zenangst** [comment]
This is ace! But would it make more sense to use strings with `.` as a delimiter?

```
self.secret <- map.path("chaos.1.way.light.1")?.property("secret")
```

What do you think?

**Comment by zenangst** [comment]
@RamonGilabert you might find this PR interesting

**Comment by onmyway133** [comment]
@zenangst so that we need to introduce something like `KeyPathConvertible` 😁

**Comment by zenangst** [comment]
@onmyway133 something like that, which approach do you like more?

**Comment by onmyway133** [comment]
@zenangst so we have 2 ways 😄

**Comment by zenangst** [comment]
@onmyway133 this is great!

**Comment by RamonGilabert** [comment]
Good job dude.

**Pull request merged**
